name:                odd
version:             0.1.0.0
github:              "even-is-odd/odd"
license:             BSD3
author:              "Claudio Nicoli Pannacci"
maintainer:          "claudio.nicoli@pannac.ci"
copyright:           "2022 Claudio Pannacci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/even-is-odd/odd#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  odd-hello:
    main:                Hello.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - odd

tests:
  odd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - odd
